/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppUsersNewRouteImport } from './routes/app/users/new'
import { Route as AppUsersUserIdRouteImport } from './routes/app/users/$userId'
import { Route as AppProjectsNewRouteImport } from './routes/app/projects/new'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects/$projectId/route'
import { Route as AppUsersUserIdEditRouteImport } from './routes/app/users/$userId_.edit'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/app/projects/$projectId/tasks'
import { Route as AppProjectsProjectIdMembersRouteImport } from './routes/app/projects/$projectId/members'
import { Route as AppProjectsProjectIdCommentsRouteImport } from './routes/app/projects/$projectId/comments'
import { Route as AppProjectsProjectIdTasksNewRouteImport } from './routes/app/projects/$projectId/tasks.new'
import { Route as AppProjectsProjectIdMembersNewRouteImport } from './routes/app/projects/$projectId/members.new'
import { Route as AppProjectsProjectIdCommentsNewRouteImport } from './routes/app/projects/$projectId/comments.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/users/$userId_/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdMembersRoute =
  AppProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdCommentsRoute =
  AppProjectsProjectIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdTasksNewRoute =
  AppProjectsProjectIdTasksNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsProjectIdTasksRoute,
  } as any)
const AppProjectsProjectIdMembersNewRoute =
  AppProjectsProjectIdMembersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsProjectIdMembersRoute,
  } as any)
const AppProjectsProjectIdCommentsNewRoute =
  AppProjectsProjectIdCommentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsProjectIdCommentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/projects/$projectId/comments': typeof AppProjectsProjectIdCommentsRouteWithChildren
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRouteWithChildren
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRouteWithChildren
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/projects/$projectId/comments/new': typeof AppProjectsProjectIdCommentsNewRoute
  '/app/projects/$projectId/members/new': typeof AppProjectsProjectIdMembersNewRoute
  '/app/projects/$projectId/tasks/new': typeof AppProjectsProjectIdTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/projects/$projectId/comments': typeof AppProjectsProjectIdCommentsRouteWithChildren
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRouteWithChildren
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRouteWithChildren
  '/app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/app/projects/$projectId/comments/new': typeof AppProjectsProjectIdCommentsNewRoute
  '/app/projects/$projectId/members/new': typeof AppProjectsProjectIdMembersNewRoute
  '/app/projects/$projectId/tasks/new': typeof AppProjectsProjectIdTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/users/$userId': typeof AppUsersUserIdRoute
  '/app/users/new': typeof AppUsersNewRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/projects/$projectId/comments': typeof AppProjectsProjectIdCommentsRouteWithChildren
  '/app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRouteWithChildren
  '/app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRouteWithChildren
  '/app/users/$userId_/edit': typeof AppUsersUserIdEditRoute
  '/app/projects/$projectId/comments/new': typeof AppProjectsProjectIdCommentsNewRoute
  '/app/projects/$projectId/members/new': typeof AppProjectsProjectIdMembersNewRoute
  '/app/projects/$projectId/tasks/new': typeof AppProjectsProjectIdTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/forbidden'
    | '/login'
    | '/app/dashboard'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/users/$userId'
    | '/app/users/new'
    | '/app/projects'
    | '/app/users'
    | '/app/projects/$projectId/comments'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId/tasks'
    | '/app/users/$userId/edit'
    | '/app/projects/$projectId/comments/new'
    | '/app/projects/$projectId/members/new'
    | '/app/projects/$projectId/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forbidden'
    | '/login'
    | '/app/dashboard'
    | '/app'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/users/$userId'
    | '/app/users/new'
    | '/app/projects'
    | '/app/users'
    | '/app/projects/$projectId/comments'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId/tasks'
    | '/app/users/$userId/edit'
    | '/app/projects/$projectId/comments/new'
    | '/app/projects/$projectId/members/new'
    | '/app/projects/$projectId/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/forbidden'
    | '/login'
    | '/app/dashboard'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/users/$userId'
    | '/app/users/new'
    | '/app/projects/'
    | '/app/users/'
    | '/app/projects/$projectId/comments'
    | '/app/projects/$projectId/members'
    | '/app/projects/$projectId/tasks'
    | '/app/users/$userId_/edit'
    | '/app/projects/$projectId/comments/new'
    | '/app/projects/$projectId/members/new'
    | '/app/projects/$projectId/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/new': {
      id: '/app/users/new'
      path: '/users/new'
      fullPath: '/app/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/$userId': {
      id: '/app/users/$userId'
      path: '/users/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/$userId_/edit': {
      id: '/app/users/$userId_/edit'
      path: '/users/$userId/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId/tasks': {
      id: '/app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/app/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/members': {
      id: '/app/projects/$projectId/members'
      path: '/members'
      fullPath: '/app/projects/$projectId/members'
      preLoaderRoute: typeof AppProjectsProjectIdMembersRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/comments': {
      id: '/app/projects/$projectId/comments'
      path: '/comments'
      fullPath: '/app/projects/$projectId/comments'
      preLoaderRoute: typeof AppProjectsProjectIdCommentsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/tasks/new': {
      id: '/app/projects/$projectId/tasks/new'
      path: '/new'
      fullPath: '/app/projects/$projectId/tasks/new'
      preLoaderRoute: typeof AppProjectsProjectIdTasksNewRouteImport
      parentRoute: typeof AppProjectsProjectIdTasksRoute
    }
    '/app/projects/$projectId/members/new': {
      id: '/app/projects/$projectId/members/new'
      path: '/new'
      fullPath: '/app/projects/$projectId/members/new'
      preLoaderRoute: typeof AppProjectsProjectIdMembersNewRouteImport
      parentRoute: typeof AppProjectsProjectIdMembersRoute
    }
    '/app/projects/$projectId/comments/new': {
      id: '/app/projects/$projectId/comments/new'
      path: '/new'
      fullPath: '/app/projects/$projectId/comments/new'
      preLoaderRoute: typeof AppProjectsProjectIdCommentsNewRouteImport
      parentRoute: typeof AppProjectsProjectIdCommentsRoute
    }
  }
}

interface AppProjectsProjectIdCommentsRouteChildren {
  AppProjectsProjectIdCommentsNewRoute: typeof AppProjectsProjectIdCommentsNewRoute
}

const AppProjectsProjectIdCommentsRouteChildren: AppProjectsProjectIdCommentsRouteChildren =
  {
    AppProjectsProjectIdCommentsNewRoute: AppProjectsProjectIdCommentsNewRoute,
  }

const AppProjectsProjectIdCommentsRouteWithChildren =
  AppProjectsProjectIdCommentsRoute._addFileChildren(
    AppProjectsProjectIdCommentsRouteChildren,
  )

interface AppProjectsProjectIdMembersRouteChildren {
  AppProjectsProjectIdMembersNewRoute: typeof AppProjectsProjectIdMembersNewRoute
}

const AppProjectsProjectIdMembersRouteChildren: AppProjectsProjectIdMembersRouteChildren =
  {
    AppProjectsProjectIdMembersNewRoute: AppProjectsProjectIdMembersNewRoute,
  }

const AppProjectsProjectIdMembersRouteWithChildren =
  AppProjectsProjectIdMembersRoute._addFileChildren(
    AppProjectsProjectIdMembersRouteChildren,
  )

interface AppProjectsProjectIdTasksRouteChildren {
  AppProjectsProjectIdTasksNewRoute: typeof AppProjectsProjectIdTasksNewRoute
}

const AppProjectsProjectIdTasksRouteChildren: AppProjectsProjectIdTasksRouteChildren =
  {
    AppProjectsProjectIdTasksNewRoute: AppProjectsProjectIdTasksNewRoute,
  }

const AppProjectsProjectIdTasksRouteWithChildren =
  AppProjectsProjectIdTasksRoute._addFileChildren(
    AppProjectsProjectIdTasksRouteChildren,
  )

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdCommentsRoute: typeof AppProjectsProjectIdCommentsRouteWithChildren
  AppProjectsProjectIdMembersRoute: typeof AppProjectsProjectIdMembersRouteWithChildren
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRouteWithChildren
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdCommentsRoute:
      AppProjectsProjectIdCommentsRouteWithChildren,
    AppProjectsProjectIdMembersRoute:
      AppProjectsProjectIdMembersRouteWithChildren,
    AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRouteWithChildren,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersNewRoute: AppUsersNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
